Repository txpipe/oura, pull requests merged in 2022-01, with the labels that each got.

#42 feat: Auto-detect version
  src/bin/oura/main.rs
Labels: enhancement

#49 feat: Add CIP-25 metadata parser
  src/filters/fingerpint.rs
  src/framework.rs
  src/mapper/cip25.rs
  src/mapper/crawl.rs
  src/mapper/map.rs
  src/mapper/mod.rs
  src/sinks/terminal/format.rs
Labels: enhancement

#51 feat: Introduce "Webhook" sink
  Cargo.lock
  Cargo.toml
  README.md
  src/bin/oura/daemon.rs
  src/filters/fingerpint.rs
  src/framework.rs
  src/sinks/mod.rs
  src/sinks/terminal/format.rs
  src/sinks/webhook/mod.rs
  src/sinks/webhook/run.rs
  src/sinks/webhook/setup.rs
Labels: enhancement

#83 docs: Add contributing guide
  .github/CONTRIBUTING.md
  README.md
Labels: documentation

#91 ci(style): Add EditorConfig and relevant GH Action
  .editorconfig
  .github/CONTRIBUTING.md
  .github/chglog/RELEASE.tpl.md
  .github/chglog/release.yml
  .github/workflows/mdbook.yml
  .github/workflows/release.yml
  .github/workflows/validate.yml
  README.md
  book/.gitignore
  book/src/SUMMARY.md
  book/src/filters/README.md
  book/src/filters/selection.md
  book/src/guides/README.md
  book/src/guides/cardano_2_kafka.md
  book/src/installation/README.md
  book/src/installation/kubernetes.md
  book/src/reference/README.md
  book/src/sinks/README.md
  book/src/sinks/elastic.md
  book/src/sinks/webhook.md
  book/src/sources/README.md
  book/src/usage/README.md
  book/src/usage/daemon.md
  book/src/usage/watch.md
  rustfmt.toml
  testdrive/cardano2elastic/k8s/elastic.yaml
  testdrive/cardano2elastic/k8s/oura.yaml
  testdrive/cardano2elastic/skaffold.yaml
  testdrive/cardano2webhook/README.md
  testdrive/cardano2webhook/k8s/endpoint.yaml
  testdrive/cardano2webhook/skaffold.yaml
Labels: enhancement, automation

#101 fix: Slot to timestamp mapping matches public explorers
  src/mapper/prelude.rs
  src/sources/n2c/run.rs
  src/sources/n2n/run.rs
  src/utils/mod.rs
  src/utils/time.rs
Labels: enhancement

#96 ci(feat): Start linting both code and some support files
  .github/workflows/validate.yml
Labels: enhancement, automation

#109 Make `mod model` public
  src/filters/fingerprint.rs
  src/filters/selection.rs
  src/lib.rs
  src/mapper/cip25.rs
  src/mapper/collect.rs
  src/mapper/crawl.rs
  src/mapper/map.rs
  src/mapper/prelude.rs
  src/model.rs
  src/pipelining.rs
  src/sinks/elastic/run.rs
  src/sinks/kafka/run.rs
  src/sinks/terminal/format.rs
  src/sinks/webhook/run.rs
  src/sources/common.rs
  src/sources/n2c/run.rs
  src/sources/n2n/run.rs
  src/utils/mod.rs
Labels: enhancement

#108 refactor: Streamline access shared utilities
  src/bin/oura/daemon.rs
  src/bin/oura/dump.rs
  src/bin/oura/watch.rs
  src/lib.rs
  src/mapper/crawl.rs
  src/mapper/map.rs
  src/mapper/prelude.rs
  src/sources/common.rs
  src/sources/n2c/setup.rs
  src/sources/n2n/setup.rs
  src/utils/bech32.rs
  src/utils/mod.rs
  src/utils/time.rs
Labels: enhancement
