Repository txpipe/oura, pull requests merged in 2022-02, with the labels that each got.

#129 ci: Remove i686 release targets
  .github/workflows/release.yml
Labels: enhancement, automation

#127 feat: Add option to include raw block cbor
  src/mapper/crawl.rs
  src/mapper/map.rs
  src/mapper/prelude.rs
  src/model.rs
  src/sources/n2c/run.rs
  src/sources/n2n/run.rs
Labels: enhancement

#130 ci(dependabot): Auto-update GH Action versions
  .github/dependabot.yml
Labels: enhancement, dependencies, automation

#138 feat: pallas byron
  Cargo.lock
  Cargo.toml
  src/mapper/byron.rs
  src/mapper/cip25.rs
  src/mapper/collect.rs
  src/mapper/map.rs
  src/mapper/mod.rs
  src/mapper/shelley.rs
  src/sources/common.rs
  src/sources/n2c/blocks.rs
  src/sources/n2c/mod.rs
  src/sources/n2c/run.rs
  src/sources/n2c/setup.rs
  src/sources/n2n/headers.rs
  src/sources/n2n/mod.rs
  src/sources/n2n/run.rs
  src/sources/n2n/setup.rs
  src/utils/mod.rs
Labels: enhancement

#140 feat: Introduce the 'Assert' sink
  src/bin/oura/daemon.rs
  src/sinks/assert/checks.rs
  src/sinks/assert/mod.rs
  src/sinks/assert/prelude.rs
  src/sinks/assert/run.rs
  src/sinks/assert/setup.rs
  src/sinks/mod.rs
Labels: enhancement, automation

#148 chore: Upgrade to Pallas 0.5.0-alpha.1
  .gitignore
  Cargo.lock
  Cargo.toml
  src/sources/n2c/blocks.rs
  src/sources/n2c/run.rs
  src/sources/n2n/headers.rs
  src/sources/n2n/run.rs
Labels: dependencies

#149 feat: Implement rollback buffer
  Cargo.lock
  Cargo.toml
  src/bin/oura/dump.rs
  src/bin/oura/watch.rs
  src/sources/n2c/blocks.rs
  src/sources/n2c/run.rs
  src/sources/n2c/setup.rs
  src/sources/n2n/run.rs
  src/sources/n2n/setup.rs
Labels: enhancement

#153 chore: Update Pallas to version 0.5.0-alpha.3
  Cargo.lock
  Cargo.toml
  src/sources/n2c/blocks.rs
  src/sources/n2c/run.rs
  src/sources/n2n/headers.rs
  src/sources/n2n/run.rs
Labels: dependencies

#155 feat: Implement multi-era time
  src/mapper/prelude.rs
  src/utils/mod.rs
  src/utils/time.rs
Labels: enhancement

#166 fix: Use magic from source in daemon bootstrap
  src/bin/oura/daemon.rs
  src/sources/common.rs
Labels: bug
